### ISSUE TITLE
노트 목록 데이터 수집

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/ACM-Backend#1]
## 💡 Idea
- 크롤링 대상 사이트에서 향수의 노트 데이터를 크롤링한다.
- 노트 그룹과 노트 데이터를 수집한다.
- 노트 그룹 : 그룹 이름, 설명 등...
- 노트 목록 : 노트 이름, 이미지, 상세 페이지 url 등...

<br>

## 📌 Task List
- [x] 노트 그룹 목록 수집하기
- [x] 노트 목록 수집하기
- [x] 노트 그룹, 노트 매핑

<br>

> #### Reference
> 크롤링 대상 사이트(https://www.fragrantica.com)

**Comment by xyzzeong** [comment]
### 해성님 작업 결과

- 노트 그룹 : 13개
- 노트 : 1,101개 (1,097개 - 이름으로 중복제거시)

#### 현재까지 얻은 데이터
- 노트 그룹 목록 (그룹 이름, 그룹 설명)
- 노트 목록 (이름, 섬네일, detail page 링크)

**Comment by junhaesung** [comment]
#60 에서 작업 완료

**Comment by junhaesung** [comment]
```
SELECT count(*) FROM perfuming_dev.note_group;
# 13 
SELECT count(*) FROM perfuming_dev.note; 
# 1122
```
