### ISSUE TITLE
모듈 분리

### ISSUE THREAD

**Issue by junhaesung** [mash-up-kr/ACM-Backend#11]
## 💡 Idea
- api, batch, admin 등 서로 다른 어플리케이션을 각각 모듈로 분리함

<br>

## 📌 Task List
- [ ] domain, batch 모듈 추가
- [ ] api 모듈 추가
- [ ] admin 모듈 추가

<br>
