### ISSUE TITLE
향수 목록 데이터 수집

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/ACM-Backend#2]
## 💡 Idea
- 크롤링 대상 사이트에서 모든 향수 데이터를 크롤링한다.
    - 현재 데이터 67,000개 이상, 계속해서 추가되고 있음
- 향수 목록 : 향수 이름, 이미지, 상세 페이지 url 등...
- 크롤링 대상 사이트에서는 목록에서 데이터를 1,000개까지만 가져올 수 있다.
    - 필터나 검색을 이용하여 데이터를 쪼개서 가져와야 함
    - 이 방법에 대해서 고민과 논의 필요함

<br>

## 📌 Task List
- [x] 향수 목록 수집하기
- [x] 향수 검색 조건(필터, 검색 단어) 구성하기

<br>

> #### Reference
> 크롤링 대상 사이트(https://www.fragrantica.com)

**Comment by junhaesung** [comment]
- [ ] jenkins 에서 배치 어플리케이션 실행시 selenium 동작가능하게 chrome 설치해야함
