### ISSUE TITLE
향수 & 노트 URL 데이터 수집 및 매핑

### ISSUE THREAD

**Issue by xyzzeong** [mash-up-kr/ACM-Backend#3]
## 💡 Idea
- 향수 상세 페이지 url 데이터를 수집한다.
- 노트 url 데이터를 수집한다.
- 향수와 노트 데이터를 매핑한다.

<br>

## 📌 Task List
- [x] top, middle, base note 데이터 있는 향수 샘플 데이터 찾기
- [ ] note 종류 구분없는 향수 샘플 데이터 찾기
- [ ] 향수 상세 페이지 URL 수집하기
- [ ] 노트 URL 수집하기
- [ ] 향수와 노트 매핑하기

<br>

> #### Reference
> 크롤링 대상 사이트(https://www.fragrantica.com)
